name: Debug build

on:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.18
      - name: Native Build
        run: | 
          go install -v golang.org/x/mobile/cmd/gomobile@latest
          go install -v golang.org/x/mobile/cmd/gobind@latest
          ./run lib core
          cd libcore/ && source .github/env.sh
          gomobile bind -v -trimpath -ldflags='-s -w' . || exit 1
          rm -r libcore-sources.jar
          proj=../app/libs
          mkdir -p $proj
          cp -f libcore.aar $proj
          echo ">> install $(realpath $proj)/libcore.aar"
      - name: Debug build
        env:
          BUILD_PLUGIN: none
        run: |
          echo "sdk.dir=${ANDROID_HOME}" > local.properties
          echo "ndk.dir=${ANDROID_HOME}/ndk/23.1.7779620" >> local.properties
          ./run init action library
          ./gradlew :app:assembleOssDebug
      - uses: actions/upload-artifact@v2
        with:
          name: Matsuri-1.0.0-arm64-v8a-debug.apk
          path: ./app/build/outputs/apk/oss/debug/Matsuri-1.0.0-arm64-v8a-debug.apk
