name: Debug build

on:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Setup Go mobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init
          git clone https://github.com/MatsuriDayo/v2ray-core
          cd libcore/ && go mod download && gomobile bind -v -o libcore.aar -target=android ./
      - name: Native Build
        run: ./run init action go && ./run lib core
      - name: Debug build
        env:
          BUILD_PLUGIN: none
        run: |
          echo "sdk.dir=${ANDROID_HOME}" > local.properties
          echo "ndk.dir=${ANDROID_HOME}/ndk/23.1.7779620" >> local.properties
          ./run init action library
          ./gradlew :app:assembleOssDebug
