name: Debug build

on:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Native Build
        run: ./run init action go && ./run lib core
      - name: Debug build
        env:
          BUILD_PLUGIN: none
        run: |
          echo "sdk.dir=${ANDROID_HOME}" > local.properties
          echo "ndk.dir=${ANDROID_HOME}/ndk/23.1.7779620" >> local.properties
          ./run init action library
          ./gradlew :app:assembleOssDebug
