name: test

on:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: GO
        uses: actions/setup-go@v3
      - name: test
        run: cd libcore && rm -rf go.mod && rm -rf go.sum && go mod init libcore && go mod tidy
